<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>true</IsPackable>
    <Authors>CleanCode-Labs, Aves Nobles</Authors>
    <PackageId>AN.MediatR.Extensions.Autofac.DependencyInjection</PackageId>
    <Title>AN.MediatR Autofac Dependency Injection</Title>
    <Description>Autofac integration for AN.MediatR.</Description>
    <PackageTags>AN.MediatR;Autofac;Mediator;IoC;CQRS</PackageTags>
    <Copyright>Copyright 2018 CleanCode-Labs. Adaptation copyright Aves Nobles.</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <MinVerTagPrefix>v</MinVerTagPrefix>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AN.MediatR\AN.MediatR.csproj" />
    <PackageReference Include="Autofac" Version="9.1.0" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
    <PackageReference Include="MinVer" Version="6.0.0" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <None Include="THIRD-PARTY-NOTICES.txt" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
